[2025-05-21T03:37:40.532+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.upload_s3 manual__2025-05-21T03:37:37.970747+00:00 [queued]>
[2025-05-21T03:37:40.537+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.upload_s3 manual__2025-05-21T03:37:37.970747+00:00 [queued]>
[2025-05-21T03:37:40.537+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-21T03:37:40.544+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): upload_s3> on 2025-05-21 03:37:37.970747+00:00
[2025-05-21T03:37:40.547+0000] {standard_task_runner.py:57} INFO - Started process 71 to run task
[2025-05-21T03:37:40.550+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'upload_s3', 'manual__2025-05-21T03:37:37.970747+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpmn6bgquq']
[2025-05-21T03:37:40.552+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask upload_s3
[2025-05-21T03:37:40.577+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.upload_s3 manual__2025-05-21T03:37:37.970747+00:00 [running]> on host 678d33baa27b
[2025-05-21T03:37:40.617+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='upload_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T03:37:37.970747+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T03:37:37.970747+00:00'
[2025-05-21T03:37:41.571+0000] {logging_mixin.py:151} INFO - Error creating bucket: The AWS Access Key Id you provided does not exist in our records.
[2025-05-21T03:37:41.572+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 13, in upload_s3_pipeline
    upload_file_to_s3(s3, file_name, AWS_BUCKET_NAME, file_name.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2025-05-21T03:37:41.579+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=upload_s3, execution_date=20250521T033737, start_date=20250521T033740, end_date=20250521T033741
[2025-05-21T03:37:41.588+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task upload_s3 ('NoneType' object has no attribute 'split'; 71)
[2025-05-21T03:37:41.599+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T03:37:41.609+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
