[2025-05-21T03:32:38.675+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.upload_s3 manual__2025-05-21T03:32:35.640328+00:00 [queued]>
[2025-05-21T03:32:38.681+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.upload_s3 manual__2025-05-21T03:32:35.640328+00:00 [queued]>
[2025-05-21T03:32:38.681+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-21T03:32:38.688+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): upload_s3> on 2025-05-21 03:32:35.640328+00:00
[2025-05-21T03:32:38.691+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2025-05-21T03:32:38.694+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'upload_s3', 'manual__2025-05-21T03:32:35.640328+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp75exvjaw']
[2025-05-21T03:32:38.695+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask upload_s3
[2025-05-21T03:32:38.721+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.upload_s3 manual__2025-05-21T03:32:35.640328+00:00 [running]> on host 678d33baa27b
[2025-05-21T03:32:38.758+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='upload_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T03:32:35.640328+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T03:32:35.640328+00:00'
[2025-05-21T03:32:39.813+0000] {logging_mixin.py:151} INFO - Error creating bucket: The AWS Access Key Id you provided does not exist in our records.
[2025-05-21T03:32:39.814+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 13, in upload_s3_pipeline
    upload_file_to_s3(s3, file_name, AWS_BUCKET_NAME, file_name.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2025-05-21T03:32:39.826+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=upload_s3, execution_date=20250521T033235, start_date=20250521T033238, end_date=20250521T033239
[2025-05-21T03:32:39.839+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task upload_s3 ('NoneType' object has no attribute 'split'; 63)
[2025-05-21T03:32:39.867+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T03:32:39.886+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
